server:
  port: 8090

jwt.secretkey: ${JWT_SECRET}

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/2025pj
    username: root
    password: admin1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# Mail properties

# spring.mail.hostsmtp.gmail.com
# spring.mail.port=587
# spring.mail.username=${SUPPORT_EMAIL}
# spring.mail.password=${APP_PASSWORD}
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true